### ISSUE TITLE
How to QC the input data and make the model.txt.

### ISSUE THREAD

**Issue by kizzhengwangshan** [Shuhua-Group/ArchaicSeeker2.0#2]
Thanks your wonderful work give me a new nemethod to deal with my job.here, i have a 2 questions,when we make the input file waht's  QCs need to be considerated,like the MAF ,Genotyping rate ,HWE et,? 2,How to generate the model.txt,in my idea, need the whole genome data to generate the “Newick” tree with population(group) that  we used for analysis?. Thanks again,Looking forward to your reply.

**Comment by Zhang-Rui-2018** [comment]
For the first question, filtrations like HWE to control the quality of sequencing data can be implemented, but MAF is not recommended.
For the second question, we have provided the example model in the example data or you can refer to the protocol.
