### ISSUE TITLE
ArchaicSeeker2: data.cpp:500: void genome::vcfsLoad(const std::vector<std::__cxx11::basic_string<char> >&): Assertion `tpos > prePos' failed.

### ISSUE THREAD

**Issue by rabbitdsy** [Shuhua-Group/ArchaicSeeker2.0#3]
When I followed the SOP from CELL STAR PROTOCALs "Detecting archaic introgression and modeling multiple-wave admixture with ArchaicSeeker 2.0", the problem occered when running the script _./ArchaicSeeker2 -v test/vcf.par -r test/remap.par -p test/pop.par -X test/outgroup.par -A test/anc.par -m test/model.txt -o test/EAS]_ 

I downloaded the Neanderthal, Denisovan, and YRI vcfs from the links in your manuscript, and without any further change.
I wonder do I need do any formatting or use other softwares to make the downloaded genotypes consistent with the input?

**Comment by Zhang-Rui-2018** [comment]
Please make sure that the physical positions are strictly increasing and not be duplicated.

**Comment by imdanique** [comment]
@rabbitdsy 
Hi! Sorry, I know that it's been a while since your question, but did you manage to solve it? I have the same problem. Thanks!
