### ISSUE TITLE
data.cpp:551: void genome::vcfsLoad(const std::vector<std::__cxx11::basic_string<char> >&): Assertion `idContigFileCheck[curID].count(*it) == 0' failed

### ISSUE THREAD

**Issue by LDS-axel** [Shuhua-Group/ArchaicSeeker2.0#4]
I have keep only biallelic SNPs and sort all the position according to physical location, why error occurs?

**Comment by Zhang-Rui-2018** [comment]
Please check your population annotation file, like the Individual ID, Population ID, and the label of ArchaicSeekerPop. This error message means that the sample size of certain population is zero.

**Comment by LDS-axel** [comment]
Thank you for your kind help, problem has been resolved
