### ISSUE TITLE
How should I process the Archaic Variants datasets? the size of Archaic vcf file provided by example seems much smaller than that from 1000 genome

### ISSUE THREAD

**Issue by LDS-axel** [Shuhua-Group/ArchaicSeeker2.0#5]
![image](https://github.com/Shuhua-Group/ArchaicSeeker2.0/assets/60178030/845745ba-7886-40b4-a41f-e3900da8a4a6)
![image](https://github.com/Shuhua-Group/ArchaicSeeker2.0/assets/60178030/8af12d60-67f4-4348-bf5f-306f90660281)

**Comment by Zhang-Rui-2018** [comment]
These data has been combined with KGP which means the remaining physical positions are the intersection of archaic data and KGP data.
