### ISSUE TITLE
how to make the outgroup file chr22.hg19.chimp.fa.gz?

### ISSUE THREAD

**Issue by LDS-axel** [Shuhua-Group/ArchaicSeeker2.0#6]
Does it means the homologous sequences between chimp genome and hg19?

**Comment by Zhang-Rui-2018** [comment]
It means that the reference version of chimp genome is hg19.
The data can be downloaded from the following website (https://drive.google.com/drive/folders/115LSXmYDlitNKDO58SgxbEYlNd4EG1WK). Please refer to our Star Protocols paper (https://doi.org/10.1016/j.xpro.2022.101314).
