### ISSUE TITLE
Error about duplicate sites from  Archaic vcf

### ISSUE THREAD

**Issue by jackzhong1995** [Shuhua-Group/ArchaicSeeker2.0#9]
Hi,

I download ancient  vcf files from your protocol suggestion. I want to known how do you deal with the ancient  vcf files, as it contain duplicate sites that will cause ArchaicSeeker error?  Is there any code can solve it?

![image](https://github.com/Shuhua-Group/ArchaicSeeker2.0/assets/101613672/134d7f76-5cbc-4bce-8d89-ea3fd599a479)

Best wishes.
jackzhong

**Comment by jackzhong1995** [comment]
well, I have solved this trouble about duplicated sites using my personal script. 

But another problem occured like this after Loading genotype information correctly:

ArchaicSeeker2: seeker.cpp:170: void archaicSeekerHMM(archaicSeekerPar&, const genomePar&): Assertion `popCorrespond.count(data.comPop[i]) failed.

How to solve it?

Best.

**Comment by yorkklause** [comment]
Hi jackzhong,

I apologize for the late response; I am not on this email list.

Regarding your issue, it seems that the "pop.par" file and the "model.txt" file are inconsistent. Specifically, any populations present in the second column of the "pop.par" file should also be present in the "model.txt" file.

If you could share all your configuration files, we could further diagnose this.

Thank you,

Kai Yuan
